# Site settings
title: Dr. S Balakrishnan
description: 'Professor and Head, Department of Computer Science and Business Systems at Sri Krishna College of Engineering and Technology, Coimbatore, Tamilnadu, India'
url: 'https://drbalakrishnan.github.io/'
baseurl: ''
# google_analytics: 'UA-XXXXXX-X'

author:
  name: 'Dr. S Balakrishnan'
  email: balkiparu@gmail.com
  twitter_username: balkiparu
  linkedin_username:  dr-balakrishnan-s-11970726
  google_scholar: https://scholar.google.co.in/citations?user=E_JorpwAAAAJ&hl=en
  scopus_name: https://www.scopus.com/authid/detail.uri?authorId=7102944084

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 8
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
